name: Update TOTD

on:
  workflow_dispatch:
  schedule:
    - cron: "18 18 * * *"  # Runs every day at 18:00 UTC = 1:00 PM EST


jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PUBLIC_DIR: .
      DEBUG: "0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run TOTD fetcher
        run: |
          echo "Running TOTD fetcher..."
          node -v
          node scripts/totd-fetcher.js
          echo ""
          echo "Listing generated files:"
          ls -R data/totd || true
          echo ""
          echo "Root snapshot:"
          ls -l totd.json || true

      - name: Commit updated TOTD data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Only stage TOTD-related files
          git add totd.json data/totd/*.json 2>/dev/null || true

          if ! git diff --cached --quiet; then
            echo "Changes detected — committing updates."
            git commit -m "data: refresh TOTD"
            git push
          else
            echo "No changes to commit."
          fi
